### ISSUE TITLE
Try to install this repo with pod

### ISSUE THREAD

**Issue by vfernandes0408** [bitmovin/bitmovin-player-ios-analytics-conviva#24]
When i try to install repo via pods i received a message [!] No `Podfile' found in the project directory.

I tried with branch(master, develop and release) and always return same message.

**Comment by stonko1994** [comment]
From the error message it seems that you are running the command `pod install` in a directory where there is no `Podfile`.

If you are trying to run our example you need to navigate into the `bitmovin-player-ios-analytics-conviva/Example` folder.

**Comment by dweinber** [comment]
As there was no further feedback we assume this resolved your problem, closing this ticket.
